name = "SparsityDetection"
uuid = "684fba80-ace3-11e9-3d08-3bc7ed6f96df"
authors = ["Shashi Gowda", "Chris Rackauckas <contact@chrisrackauckas.com>"]
version = "0.3.1"

[deps]
Cassette = "7057c7e9-c182-5462-911a-8362d720325c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
Cassette = "0.2, 0.3"
SpecialFunctions = "0.8, 0.9, 0.10"
julia = "1"

[extras]
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["FiniteDiff", "SafeTestsets", "Test"]
